# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.8"
   
services:
    django:
        build: .
        container_name: django_container
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django_dir
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        # image: postgres
        # container_name: pgdb_container
        # environment:
        # - POSTGRES_DB=postgres
        # - POSTGRES_USER=postgres_user
        # - POSTGRES_PASSWORD=postgres 
        # volumes:
        #     - ./data/db:/var/lib/postgresql/data
        # healthcheck:
        #     test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            # interval: 1m30s
            # timeout: 30s
            # retries: 5
            # start_period: 30s

        image: mysql:5.7
        container_name: mysqldb_container
        environment:
            - MYSQL_DATABASE=django-app-db
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - ./data/mysql/db:/var/lib/mysql
